language: node_js
node_js: stable
branches:
  only:
    - master # build master branch only

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli   

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git hexo-renderer-pug hexo-renderer-stylus --save

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "evanliu3594"
  - git config user.email "yogi3594@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy